// HDSC Multi-Concept Website Design Exploration — concept content and scoring data.
// 13 concepts: the original 12 Archetype x Visual-Theme concepts, plus a 13th concept
// ("The Enterprise Grid") built to match the look and feel of the live Wix site at
// https://sweetbrandclothingco.wixsite.com/heavy-duty-securit-2

const FIELD_ORDER = [
  ["summary", "Concept Summary"],
  ["strategicPurpose", "Strategic Purpose"],
  ["targetCustomer", "Target Customer"],
  ["emotionalPromise", "Emotional Promise"],
  ["heroHeadline", "Hero Headline"],
  ["subheadline", "Subheadline"],
  ["primaryCTA", "Primary CTA"],
  ["secondaryCTA", "Secondary CTA"],
  ["urgencyMessage", "Urgency Message"],
  ["trustMessage", "Trust Message"],
  ["expertiseMessage", "Expertise Message"],
  ["differentiation", "Differentiation"],
  ["marketplaceExplanation", "Marketplace Explanation"],
  ["serviceDiscovery", "Service Discovery"],
  ["itilIntegration", "ITIL Integration"],
  ["valueCoCreation", "Value Co-Creation"],
  ["customerJourney", "Customer Journey"],
  ["navigation", "Navigation"],
  ["homepageSections", "Homepage Sections"],
  ["dashboard", "Dashboard"],
  ["mobileExperience", "Mobile Experience"],
  ["visualDesign", "Visual Design"],
  ["conversionStrategy", "Conversion Strategy"],
  ["fomoStrategy", "FOMO / Urgency Strategy"],
  ["socialProof", "Social Proof"],
  ["retentionStrategy", "Retention Strategy"],
  ["brandRecognition", "Brand Recognition"],
  ["competitiveAdvantage", "Competitive Advantage"],
];

const CONCEPTS = [
  {
    id: "signal", code: "SIG", name: "The Signal", archetype: "Hero", theme: "Sliver of Light",
    summary: "HDSC as the force that steps in and resolves the technology crisis before it becomes a business crisis. The flagship, demand-generation concept for the master HDSC brand.",
    strategicPurpose: "Serve as the flagship marketing site and primary demand-generation engine for the master HDSC brand across both on-demand and contract service lines.",
    targetCustomer: "Enterprise and government operations leaders and IT managers facing active or recurring technology risk.",
    emotionalPromise: "Relief and confidence — the moment the right help arrives.",
    heroHeadline: "Technology Problems Don't Wait. Neither Should You.",
    subheadline: "Heavy Duty Security Co. deploys engineering-grade IT and security response on your timeline, not a help desk queue.",
    primaryCTA: "Request a Technician Now",
    secondaryCTA: "See How Response Works",
    urgencyMessage: "A live countdown/response-time indicator on the hero ('Average dispatch: under 2 hours') communicates that delay has a cost.",
    trustMessage: "WOSB certification badge, CAGE/UEI credentials, and a visible ITIL-practice checklist establish institutional legitimacy alongside speed.",
    expertiseMessage: "Engineer bios emphasize CompTIA and ITIL credentials; a 'How We Resolve It' panel walks through the practice used for each incident type.",
    differentiation: "Combines consumer-grade urgency (book a technician like booking a ride) with enterprise-grade engineering discipline.",
    marketplaceExplanation: "Framed as a single trusted dispatch point that routes the request to the right credentialed engineer, whether on-demand or under contract.",
    serviceDiscovery: "A single 'What's wrong?' search/intake box auto-routes to the matching service page and technician pool.",
    itilIntegration: "Incident Management and Service Desk practices are surfaced directly in the booking flow ('ticket opened, triaged, assigned, resolved').",
    valueCoCreation: "Post-resolution, the customer receives a plain-language root-cause summary, converting a single incident into an ongoing trust relationship.",
    customerJourney: "Land on crisis-driven search term -> hero CTA -> service intake form -> technician match -> real-time status -> resolution summary -> contract upsell.",
    navigation: "Home, Services, How It Works, About, Contact/Book — flat, five-item nav built for fast conversion.",
    homepageSections: "Hero with live dispatch promise, service category grid, 'How Response Works' 4-step strip, credentials/WOSB bar, testimonials, final CTA.",
    dashboard: "A lightweight 'My Requests' portal showing ticket status, assigned engineer, and resolution history.",
    mobileExperience: "Mobile-first booking flow with a single sticky 'Request a Technician' button throughout.",
    visualDesign: "Sliver of Light treatment: dark navy ground with a single directional light shaft motif behind the hero headline, signaling clarity arriving out of a dark situation.",
    colorPalette: {
      label: "Sliver of Light — Crisis Relief",
      background: "#0B1220",
      surface: "#121A2E",
      primary: "#00D9FF",
      secondary: "#7C5CFF",
      text: "#F4F7FB",
      mutedText: "#9AA7BD",
      onPrimary: "#0B1220",
      desire: "A single electric-cyan shaft of light cutting a near-black navy field stages the brand's core promise visually: clarity arriving out of a dark situation. Violet is reserved for secondary emphasis (trust badges, credentials). The high contrast between void-black and glowing cyan triggers an approach response — relief and confidence — rather than alarm, so the hero reads as rescue, not crisis.",
    },
    conversionStrategy: "One primary action (book/request) repeated at every scroll depth; minimal competing links.",
    fomoStrategy: "Visible response-time benchmark and 'X requests resolved this week' counter create urgency without manufactured scarcity.",
    socialProof: "Client logos (anonymized by sector for public-sector clients), review quotes tied to specific incident types.",
    retentionStrategy: "Post-resolution email sequence offering a maintenance/contract tier to prevent recurrence.",
    brandRecognition: "The light-shaft motif and 'Technology Problems Don't Wait' line are reusable across all other HDSC touchpoints.",
    competitiveAdvantage: "Pairs the response speed of an on-demand platform with the documentation and compliance rigor enterprise and government buyers require.",
  },
  {
    id: "blueprint", code: "BLU", name: "The Blueprint", archetype: "Sage", theme: "Isometric",
    summary: "HDSC as the engineering authority that documents, diagrams, and standardizes IT environments — a concept built around demonstrated technical mastery.",
    strategicPurpose: "Win technically sophisticated buyers (engineering leads, CTOs, government technical evaluators) who scrutinize methodology before price.",
    targetCustomer: "Technical decision-makers evaluating a contract MSP or systems-engineering partner on rigor, not just availability.",
    emotionalPromise: "Intellectual confidence — the sense of being in genuinely expert hands.",
    heroHeadline: "Engineered Infrastructure. Documented Discipline.",
    subheadline: "Every engagement maps to an ITIL practice, a CompTIA-verified competency, and a measurable Six Sigma outcome.",
    primaryCTA: "Request a Capability Statement",
    secondaryCTA: "View Our ITIL Practice Map",
    urgencyMessage: "Understated; urgency is replaced with 'book a technical assessment' as the low-friction next step.",
    trustMessage: "Isometric system diagrams of HDSC's own service architecture are shown publicly — transparency as a trust signal.",
    expertiseMessage: "A full ITIL 5.1-5.3 practice crosswalk (to CompTIA task lines, Six Sigma belt methods, and PMBOK domains) is published as a resource.",
    differentiation: "Most MSP sites sell availability; this one sells methodology — the isometric diagram language makes the engineering visible.",
    marketplaceExplanation: "Positioned as a vetted bench of credentialed engineers assignable to defined scopes of work, not an anonymous labor pool.",
    serviceDiscovery: "Services are organized by ITIL practice group (General, Service, Technical Management) rather than by product, matching how technical buyers think.",
    itilIntegration: "Central to the concept: every service page opens with 'ITIL Practice,' 'CompTIA Competency,' and 'Six Sigma Method' labels before any sales copy.",
    valueCoCreation: "Clients receive the same isometric architecture diagram of their own environment as a deliverable, reinforcing shared technical ownership.",
    customerJourney: "Technical search term -> practice-mapped service page -> capability statement download (lead capture) -> scoping call -> SOW.",
    navigation: "Home, Capabilities, ITIL Practice Map, Case Studies, About, Contact.",
    homepageSections: "Hero with isometric diagram, 'How We Work' practice-map strip, capability statement download, case study grid, certifications.",
    dashboard: "A client-facing 'Environment Map' dashboard showing the isometric diagram of the client's own systems, kept current as engagements progress.",
    mobileExperience: "Diagrams simplify to vertical stacked panels on mobile; capability statement remains a one-tap download.",
    visualDesign: "Isometric treatment: navy/blue ground, isometric line-art diagrams of servers, networks, and workflows as the dominant visual language, restrained color use.",
    colorPalette: {
      label: "Isometric — Engineering Authority",
      background: "#0E1B2E",
      surface: "#13233B",
      primary: "#2F6FD1",
      secondary: "#9FD8FF",
      text: "#EAF2FF",
      mutedText: "#8FA3C2",
      onPrimary: "#FFFFFF",
      desire: "Deep blueprint-navy with crisp white-blue line accents borrows the literal visual grammar of engineering blueprints and CAD drawings, so competence reads instantly and non-verbally. The restrained two-blue system (no warm colors) keeps attention on precision and documentation rather than emotion — appropriate for a Sage archetype selling trust through demonstrated mastery.",
    },
    conversionStrategy: "Gated capability-statement download as the primary lead magnet; direct booking is secondary.",
    fomoStrategy: "Minimal — intentionally low-pressure to match the Sage archetype; relies on authority rather than urgency.",
    socialProof: "Named case studies with before/after architecture diagrams rather than generic quotes.",
    retentionStrategy: "Quarterly 'environment review' diagram refresh offered as a standing engagement.",
    brandRecognition: "The isometric diagram style becomes a recognizable HDSC signature usable across proposals and reports.",
    competitiveAdvantage: "Makes HDSC's engineering methodology, normally invisible to the buyer, the actual visual and narrative center of the site.",
  },
  {
    id: "onyourside", code: "OYS", name: "On Your Side", archetype: "Caregiver", theme: "Figure Isolation",
    summary: "HDSC as the protector of small-business and nonprofit operators who feel overwhelmed and underserved by enterprise-focused IT vendors.",
    strategicPurpose: "Build trust and warmth with smaller, less technical buyers who need reassurance as much as resolution.",
    targetCustomer: "Small-business owners, office managers, and nonprofit administrators without in-house IT staff.",
    emotionalPromise: "Being looked after — someone finally has your back.",
    heroHeadline: "You Shouldn't Have to Understand IT to Be Protected By It.",
    subheadline: "We translate, we simplify, and we handle it — so you can run your business.",
    primaryCTA: "Talk to a Real Person",
    secondaryCTA: "See Plans for Small Teams",
    urgencyMessage: "Framed as risk-avoidance ('don't wait for a breach to find a partner') rather than countdown urgency.",
    trustMessage: "Plain-language guarantees, a named point-of-contact promise, and visible WOSB/small-business credentials.",
    expertiseMessage: "Expertise is shown through translation, not jargon — 'what this means for you' callouts next to any technical term.",
    differentiation: "Most MSPs speak to IT managers; this concept speaks directly to the non-technical owner who has no one else to ask.",
    marketplaceExplanation: "Presented as a single caring relationship, not a marketplace — one assigned team that gets to know the client's business.",
    serviceDiscovery: "A short, friendly quiz ('What's slowing your team down?') routes visitors to a plain-language service recommendation.",
    itilIntegration: "ITIL practices are present but renamed in plain language ('how we keep small problems from becoming big ones').",
    valueCoCreation: "Clients co-author a simple one-page 'IT health plan' with their assigned contact, revisited quarterly.",
    customerJourney: "Referral or search -> warm, human-centered landing page -> quiz or quick call -> named contact assigned -> ongoing plan.",
    navigation: "Home, How We Help, Plans, Our Team, Contact — warm, conversational labels rather than technical ones.",
    homepageSections: "Hero with human photography/figure motif, 'How We Help' in plain language, team introduction, simple pricing plans, reassurance FAQ.",
    dashboard: "A simple monthly 'How We Took Care of You' summary email/portal rather than a technical ticket dashboard.",
    mobileExperience: "Large tap targets, a visible phone number, minimal technical vocabulary throughout.",
    visualDesign: "Figure Isolation treatment: navy/periwinkle palette, a single warm human silhouette motif standing in protected light, Fraunces italic serif headlines for a personal, caring tone.",
    colorPalette: {
      label: "Figure Isolation — Protected Light",
      background: "#FAF9FC",
      surface: "#F0EEFA",
      primary: "#6C7FD8",
      secondary: "#E8A33D",
      text: "#2A2D3A",
      mutedText: "#5B5F72",
      onPrimary: "#FFFFFF",
      desire: "A soft, light periwinkle ground (rather than the Signal/Blueprint dark navy) signals safety and approachability for small-business and nonprofit buyers who feel overlooked by enterprise IT vendors. A single warm amber accent represents the 'protected light' around the human silhouette motif — warmth breaks through the cool palette the way help arrives for someone who has been struggling alone.",
    },
    conversionStrategy: "Phone call and quiz completion are weighted equally with form submission as conversions.",
    fomoStrategy: "Soft — 'most small businesses wait until something breaks; let's talk before that happens.'",
    socialProof: "Named small-business owner testimonials with recognizable local business types (clinic, nonprofit, retailer).",
    retentionStrategy: "A named, consistent point of contact is the retention mechanism rather than a loyalty program.",
    brandRecognition: "The protective figure-silhouette motif and warm serif type are distinct from HDSC's more technical concepts.",
    competitiveAdvantage: "Wins the segment of buyers who are put off by technical MSP marketing and want to feel cared for, not sold to.",
  },
  {
    id: "commandline", code: "CMD", name: "Command Line", archetype: "Magician", theme: "Redline",
    summary: "HDSC as the transformative technical force that turns a chaotic, failing environment into a controlled, high-performing one.",
    strategicPurpose: "Appeal to buyers mid-crisis or mid-transformation who want a decisive technical intervention, not a vendor relationship.",
    targetCustomer: "IT directors undertaking a major modernization, migration, or security overhaul under pressure.",
    emotionalPromise: "Transformation — watching a broken system become powerful.",
    heroHeadline: "We Don't Patch Problems. We Transform Systems.",
    subheadline: "Full-stack engineering intervention — security, infrastructure, and process — delivered as one decisive engagement.",
    primaryCTA: "Start Your Transformation",
    secondaryCTA: "See a Before / After",
    urgencyMessage: "Framed around the cost of staying broken ('every week on legacy infrastructure is a week of compounding risk').",
    trustMessage: "Before/after metrics (uptime, incident rate, cost) presented as proof of transformation, not just completion.",
    expertiseMessage: "A 'diagnostic to deployment' methodology page shows the full engineering sequence used in major engagements.",
    differentiation: "Positions HDSC as a transformation partner for a defined engagement, distinct from ongoing break-fix support.",
    marketplaceExplanation: "A curated strike-team model: a named lead engineer assembles the right specialists from HDSC's bench for the specific transformation.",
    serviceDiscovery: "Services are framed as transformation packages (Security Overhaul, Infrastructure Modernization, Compliance Readiness) rather than a long service list.",
    itilIntegration: "Change Enablement and Service Configuration Management practices anchor the transformation methodology page.",
    valueCoCreation: "A joint 90-day transformation roadmap is co-built with the client in the first engagement week.",
    customerJourney: "Crisis/initiative trigger -> transformation package page -> diagnostic request -> roadmap presentation -> engagement.",
    navigation: "Home, Transformations, Methodology, Results, Contact.",
    homepageSections: "High-contrast hero with bold claim, before/after metrics strip, transformation package cards, methodology steps, results.",
    dashboard: "A transformation-tracking dashboard showing roadmap milestones, not routine tickets.",
    mobileExperience: "Bold, high-contrast mobile hero retains full visual impact; CTA remains 'Start Your Transformation.'",
    visualDesign: "Redline treatment: dark charcoal ground, bold red accent, Oswald uppercase display type, high-contrast before/after visual blocks.",
    colorPalette: {
      label: "Redline — Transformation",
      background: "#171717",
      surface: "#1F1F1F",
      primary: "#E8142A",
      secondary: "#FF5A3C",
      text: "#F5F5F5",
      mutedText: "#A8A8A8",
      onPrimary: "#FFFFFF",
      desire: "Charcoal-black with a decisive red accent is the classic 'mark-up and correct' color pairing — it visually says something was wrong and has now been fixed. The red-to-ember gradient on before/after panels dramatizes transformation rather than danger, giving the Magician archetype's 'we transform systems' claim a color system that feels like decisive, expert intervention.",
    },
    conversionStrategy: "A single high-commitment CTA (diagnostic request) rather than multiple small conversions.",
    fomoStrategy: "Cost-of-inaction framing is the primary urgency lever, reinforced with real before/after numbers.",
    socialProof: "Case studies framed explicitly as before/after transformation stories with quantified results.",
    retentionStrategy: "Post-transformation, clients are offered a sustaining 'Keep It Transformed' maintenance contract.",
    brandRecognition: "Bold red-on-charcoal transformation branding is distinct and memorable within the HDSC portfolio.",
    competitiveAdvantage: "Speaks directly to the buyer who already knows something must change and wants a decisive partner, not a slow conversation.",
  },
  {
    id: "thefix", code: "FIX", name: "The Fix", archetype: "Outlaw", theme: "Redline",
    summary: "HDSC positioned against bloated, slow-moving IT vendors — a disruptive, no-nonsense alternative for buyers burned by bad MSPs.",
    strategicPurpose: "Win switchers — buyers actively dissatisfied with an incumbent MSP or internal IT function.",
    targetCustomer: "Operations leaders who have already been let down by a slow or unresponsive IT vendor.",
    emotionalPromise: "Vindication — finally, a vendor that doesn't waste your time.",
    heroHeadline: "Your Last IT Vendor Made Excuses. We Make Fixes.",
    subheadline: "No ticket queues. No vague SLAs. Just engineers who show up and solve it.",
    primaryCTA: "Switch to HDSC",
    secondaryCTA: "Compare Us to Your Current Vendor",
    urgencyMessage: "A direct comparison table against 'typical MSP' behavior creates urgency through contrast, not countdowns.",
    trustMessage: "A public, specific SLA (named response times, named escalation path) replaces vague promises.",
    expertiseMessage: "Blunt, confident copy voice; credentials are stated directly without hedging.",
    differentiation: "Explicitly contrarian positioning — calls out industry pain points (ticket queues, outsourced call centers, change-order delays) by name.",
    marketplaceExplanation: "Framed as cutting out the middle layer of account managers — direct access to the engineer doing the work.",
    serviceDiscovery: "A 'What's broken?' direct-entry field replaces a traditional service menu.",
    itilIntegration: "Incident and Problem Management practices are presented as the antidote to 'ticket queue' dysfunction.",
    valueCoCreation: "Clients get direct engineer contact information rather than a shared support inbox.",
    customerJourney: "Dissatisfaction with current vendor -> comparison-driven landing page -> direct contact -> rapid onboarding switch.",
    navigation: "Home, Why Switch, Services, Proof, Contact.",
    homepageSections: "Blunt hero claim, vendor-comparison table, direct-access promise, switch-process steps, testimonials from switchers.",
    dashboard: "A simple status feed showing real engineer names and direct response timestamps.",
    mobileExperience: "Comparison table collapses to a stacked card format; 'Switch to HDSC' CTA persists.",
    visualDesign: "Redline treatment pushed harder: higher contrast, blunt sans-serif headlines, red used for comparison 'X' marks against competitors.",
    colorPalette: {
      label: "Redline — Confrontational Contrast",
      background: "#0D0D0D",
      surface: "#191919",
      primary: "#FF1E3C",
      secondary: "#FFFFFF",
      text: "#EDEDED",
      mutedText: "#9C9C9C",
      onPrimary: "#FFFFFF",
      desire: "The darkest, highest-contrast palette in the family — near-black with a hotter red than Command Line and stark white used for literal comparison 'X' marks against competitor failures. This maximum-contrast pairing is deliberately combative: it creates desire through loss aversion, dramatizing exactly what a bad vendor costs before the red CTA offers the fix, matching the Outlaw archetype's disruptive, no-excuses tone.",
    },
    conversionStrategy: "Comparison table is the primary conversion driver, converting dissatisfaction directly into action.",
    fomoStrategy: "'How much is your current vendor costing you in downtime?' calculator creates urgency through quantified loss.",
    socialProof: "Testimonials explicitly framed as 'switched from [generic MSP] to HDSC' stories.",
    retentionStrategy: "A public SLA scorecard, updated regularly, keeps HDSC accountable and retention-worthy.",
    brandRecognition: "Blunt, contrarian copy voice is distinct and quotable, useful for paid ad campaigns.",
    competitiveAdvantage: "Converts competitor dissatisfaction directly into HDSC demand rather than competing on generic value propositions.",
  },
  {
    id: "frontier", code: "FRO", name: "Frontier", archetype: "Explorer", theme: "Sliver of Light",
    summary: "HDSC as the partner for organizations expanding into new technical territory — cloud migration, AI adoption, new facilities, new contracts.",
    strategicPurpose: "Capture growth-stage buyers whose need is driven by expansion rather than crisis or dissatisfaction.",
    targetCustomer: "Growing companies and agencies scaling infrastructure, adopting new technology, or standing up new locations/contracts.",
    emotionalPromise: "Momentum — the confidence to grow without technology holding you back.",
    heroHeadline: "Growing Fast? Your Infrastructure Should Keep Up.",
    subheadline: "From new site stand-ups to AI-readiness, HDSC engineers the ground you're expanding onto.",
    primaryCTA: "Plan Your Next Phase",
    secondaryCTA: "See Growth-Stage Services",
    urgencyMessage: "Tied to the client's own growth timeline ('your new contract starts in 60 days — is your infrastructure ready?').",
    trustMessage: "Scalability case studies show HDSC supporting a client through more than one growth stage.",
    expertiseMessage: "Emphasizes forward-looking competencies: cloud, AI-readiness, Systems and Software Engineering service lines.",
    differentiation: "Most MSP marketing is reactive (fix problems); this concept is proactive (enable growth).",
    marketplaceExplanation: "Framed as a scalable bench that grows with the client — add engineers and service lines as the client's footprint expands.",
    serviceDiscovery: "A 'Where are you growing?' selector (new location, new contract, new technology) routes to tailored service bundles.",
    itilIntegration: "Service Design and Capacity and Performance Management practices anchor the growth-planning narrative.",
    valueCoCreation: "A joint growth-infrastructure roadmap is built alongside the client's own business growth plan.",
    customerJourney: "Growth trigger (new contract, funding, expansion) -> growth-stage landing page -> roadmap planning call -> phased engagement.",
    navigation: "Home, Growth Services, Industries, Roadmap, Contact.",
    homepageSections: "Hero with forward-motion light-shaft visual, growth-trigger selector, service bundle cards, roadmap preview, case studies.",
    dashboard: "A phased-roadmap dashboard tracking growth milestones against infrastructure readiness.",
    mobileExperience: "Growth-trigger selector adapts to a simple tap-through flow on mobile.",
    visualDesign: "Sliver of Light treatment with a forward/diagonal light motif suggesting momentum and horizon rather than crisis.",
    colorPalette: {
      label: "Sliver of Light — Horizon",
      background: "#0E1B2B",
      surface: "#15283D",
      primary: "#FF8A3D",
      secondary: "#2FD9C4",
      text: "#F5FAFA",
      mutedText: "#93B0AE",
      onPrimary: "#0E1B2B",
      desire: "The same dark-ground Sliver of Light family as Signal, but the light motif is reframed as a sunrise on the horizon rather than a rescue beam: warm orange rising against a deep teal-navy night sky, with a cooler teal secondary for growth and momentum. The palette creates desire through aspiration and opportunity-FOMO ('what's next') rather than urgency, fitting the Explorer archetype's scaling, forward-looking buyer.",
    },
    conversionStrategy: "Roadmap planning call is the primary conversion, framed as free strategic value rather than a sales call.",
    fomoStrategy: "Tied to the client's own deadlines (contract start dates, funding timelines) rather than artificial scarcity.",
    socialProof: "Growth-stage case studies showing a client's infrastructure scaling alongside their business over time.",
    retentionStrategy: "Ongoing roadmap reviews as the company continues to grow keep HDSC embedded long-term.",
    brandRecognition: "The forward-light/horizon motif distinguishes Frontier from The Signal's crisis-response light treatment.",
    competitiveAdvantage: "Positions HDSC ahead of the client's need rather than reacting to it, a rare stance among MSP competitors.",
  },
  {
    id: "nopatience", code: "NOP", name: "No Patience for Bureaucracy", archetype: "Jester", theme: "Redline",
    summary: "An irreverent, high-energy concept that pokes fun at slow government and enterprise IT procurement while still delivering credentialed, compliant work.",
    strategicPurpose: "Cut through procurement fatigue with humor and directness, primarily as a paid-social and landing-page concept.",
    targetCustomer: "Procurement-weary buyers in government-adjacent or enterprise environments tired of slow vendor processes.",
    emotionalPromise: "Relief through humor — finally, a vendor that doesn't take itself too seriously while still being fully compliant.",
    heroHeadline: "We Filled Out the Forms So You Don't Have To.",
    subheadline: "Full compliance. Zero patience for bureaucracy. All the paperwork, none of the delay.",
    primaryCTA: "Skip the Delay",
    secondaryCTA: "See Our Compliance Docs",
    urgencyMessage: "Playful countdown framing ('this RFP closes in 4 days — good thing we're already ready').",
    trustMessage: "Compliance credentials (WOSB, UEI, CAGE) are shown, but with a wink — 'yes, we have all of these, no you don't have to ask twice.'",
    expertiseMessage: "Credentials are listed plainly beneath the humor, keeping the concept credible rather than purely comedic.",
    differentiation: "The only concept in the portfolio that uses humor as the primary emotional lever, aimed at paid-social virality.",
    marketplaceExplanation: "Framed as 'the fast lane' — the same credentialed bench, with the friction removed.",
    serviceDiscovery: "A single, short services list with blunt, funny one-liners per category.",
    itilIntegration: "Referenced lightly ('we do ITIL properly so you don't have to ask') rather than explained in depth.",
    valueCoCreation: "Not a primary feature of this concept; the focus is top-of-funnel attention, not deep engagement tooling.",
    customerJourney: "Paid social ad -> humor-driven landing page -> compliance proof -> quote request, optimized for a short, snackable funnel.",
    navigation: "Single-page scroll with anchor links: Problem, Proof, Services, Contact — minimal multi-page structure.",
    homepageSections: "Bold humorous hero, compliance-credential strip, short service list, quote-request CTA.",
    dashboard: "Not applicable — this is a top-of-funnel landing concept, not an account experience.",
    mobileExperience: "Built mobile-first for social-ad traffic; single scroll, one CTA repeated.",
    visualDesign: "Redline treatment with bolder, more playful typographic treatment — oversized text, blunt contrast, meme-adjacent pacing.",
    colorPalette: {
      label: "Redline — Irreverent Energy",
      background: "#161616",
      surface: "#202020",
      primary: "#FF3B30",
      secondary: "#FFD23F",
      text: "#FAFAFA",
      mutedText: "#B5B5B5",
      onPrimary: "#1A1500",
      desire: "Shares the Redline family's dark-and-red DNA for brand cohesion, but adds an unexpected high-energy yellow accent that no other concept uses — a visual joke/jolt that matches the Jester archetype's irreverence toward slow bureaucracy. The yellow pop on red/black creates memorability and a sense of fun confidence, making the brand feel bold enough to make fun of the paperwork it still, credibly, completes.",
    },
    conversionStrategy: "Optimized purely for quote-request volume from paid social traffic.",
    fomoStrategy: "Humor-wrapped urgency ('bureaucracy is slow, we're not') is the core mechanic.",
    socialProof: "Short, punchy testimonial one-liners rather than long case studies.",
    retentionStrategy: "Not a retention-focused concept; it exists to convert cold paid traffic into a lead for other concepts to retain.",
    brandRecognition: "High virality potential but intentionally the least 'corporate' concept — used narrowly for campaigns, not as a primary site.",
    competitiveAdvantage: "Differentiates HDSC in a category where virtually no competitor uses humor, while still proving full compliance.",
  },
  {
    id: "builtby", code: "BLT", name: "Built By", archetype: "Creator", theme: "Isometric",
    summary: "HDSC as a builder of custom technical solutions — software, infrastructure, and systems engineered specifically for the client's problem.",
    strategicPurpose: "Win custom-engineering and software-engineering engagements that a generic MSP positioning would not capture.",
    targetCustomer: "Organizations needing bespoke systems, software, or infrastructure rather than standardized support.",
    emotionalPromise: "Pride of ownership — a solution built specifically for you, not off a shelf.",
    heroHeadline: "Built for Your Problem. Not Someone Else's.",
    subheadline: "Custom software, systems, and infrastructure engineering from a team that designs around your exact requirements.",
    primaryCTA: "Start a Build",
    secondaryCTA: "See What We've Built",
    urgencyMessage: "Low urgency by design; the emphasis is on getting the build right, not getting it fast.",
    trustMessage: "A visible build methodology (discovery, design, build, validate) shown as an isometric pipeline diagram.",
    expertiseMessage: "Systems Engineering and Software Engineering service lines are given top billing over general IT support.",
    differentiation: "Distinct from the support-oriented concepts — this one sells original engineering work, not maintenance.",
    marketplaceExplanation: "Framed as a project-based engagement model: scoped builds assigned to a dedicated engineering team.",
    serviceDiscovery: "A portfolio-style gallery of past builds (anonymized where required) replaces a standard service list.",
    itilIntegration: "Service Design and Release Management practices anchor the build methodology.",
    valueCoCreation: "Clients are involved in design reviews at each build phase, reinforcing co-ownership of the final solution.",
    customerJourney: "Custom-need trigger -> portfolio/gallery browse -> discovery call -> scoped proposal -> build engagement.",
    navigation: "Home, What We Build, Our Work, Process, Contact.",
    homepageSections: "Hero with isometric build-pipeline graphic, portfolio gallery, process steps, client testimonials, contact.",
    dashboard: "A build-progress dashboard showing phase (discovery/design/build/validate) for active engagements.",
    mobileExperience: "Portfolio gallery becomes a swipeable card carousel on mobile.",
    visualDesign: "Isometric treatment applied to build/pipeline diagrams rather than infrastructure diagrams, same navy/blue palette and restrained line art.",
    colorPalette: {
      label: "Isometric — Maker's Blueprint",
      background: "#0F1B2E",
      surface: "#152440",
      primary: "#2F6FD1",
      secondary: "#FFB13C",
      text: "#EAF2FF",
      mutedText: "#8FA3C2",
      onPrimary: "#FFFFFF",
      desire: "Shares Blueprint's navy/blue isometric base — signaling the same engineering credibility — but swaps the cool white-blue secondary for a warm amber 'build' accent, evoking a workshop lamp or solder-point glow. That warmth differentiates the Creator archetype's hands-on, custom-built promise from Blueprint's more formal documentation focus, while keeping both concepts recognizably part of the same engineering sub-family.",
    },
    conversionStrategy: "Discovery call booking is the primary conversion, framed as a design conversation rather than a sales pitch.",
    fomoStrategy: "Minimal; relies on portfolio quality and specificity rather than urgency messaging.",
    socialProof: "Detailed build case studies with problem/solution/outcome structure.",
    retentionStrategy: "Post-launch support and iteration contracts are offered as a natural extension of the build relationship.",
    brandRecognition: "The build-pipeline isometric graphic is a distinct visual cousin to The Blueprint's infrastructure diagrams.",
    competitiveAdvantage: "Captures custom-engineering demand that a generic 'IT support' positioning would miss entirely.",
  },
  {
    id: "anyonesengineer", code: "ANE", name: "Anyone's Engineer", archetype: "Everyman", theme: "Essentialism",
    summary: "A plain, approachable concept presenting HDSC as straightforward, honest, and accessible IT support for any size organization.",
    strategicPurpose: "Serve as a broad, low-friction entry point for buyers who are not strongly segmented by crisis, growth, or technical sophistication.",
    targetCustomer: "General small-to-mid-size business and organizational buyers without a strong existing vendor relationship.",
    emotionalPromise: "Reassurance through normalcy — IT support that feels straightforward, not intimidating or oversold.",
    heroHeadline: "IT Support That Just Works. For Everyone.",
    subheadline: "No jargon, no upsells, no surprises — just reliable engineering-grade support at a fair price.",
    primaryCTA: "Get a Straight Answer",
    secondaryCTA: "See Simple Pricing",
    urgencyMessage: "Minimal; urgency is replaced with reassurance ('reach out whenever you need us').",
    trustMessage: "Transparent, published pricing and a plain-language service guarantee build trust through simplicity.",
    expertiseMessage: "Credentials are listed factually, without heavy emphasis, consistent with the modest Everyman voice.",
    differentiation: "Deliberately the least 'branded' concept — positioned as the dependable, no-drama choice.",
    marketplaceExplanation: "Framed simply as 'our team of engineers, ready when you need them' — marketplace mechanics are kept invisible.",
    serviceDiscovery: "A short, clearly labeled service list with plain pricing next to each item.",
    itilIntegration: "Present but unbranded — ITIL discipline is delivered, not marketed, consistent with the plain-spoken tone.",
    valueCoCreation: "A simple intake form lets clients describe their need in their own words rather than selecting from technical categories.",
    customerJourney: "General search -> plain-language homepage -> simple pricing page -> contact form -> onboarding.",
    navigation: "Home, Services, Pricing, About, Contact — the simplest navigation structure in the portfolio.",
    homepageSections: "Plain hero statement, service list with pricing, simple 'why us' section, contact form.",
    dashboard: "A basic account page showing active services and invoices — no gamification or technical dashboards.",
    mobileExperience: "Clean, minimal mobile layout prioritizing legibility and simple navigation over visual flourish.",
    visualDesign: "Essentialism treatment: near-monochrome white/navy, Oswald display type, grid-line dividers, minimal ornamentation throughout.",
    colorPalette: {
      label: "Essentialism — Plain Trust",
      background: "#FFFFFF",
      surface: "#F3F5F8",
      primary: "#1B3A6B",
      secondary: "#3D8BFF",
      text: "#1A1A1A",
      mutedText: "#5A6472",
      onPrimary: "#FFFFFF",
      desire: "A near-monochrome white/navy system with almost no ornamentation removes any sense of salesmanship or hype, which is itself the desire-creator for the Everyman buyer: the plainness reads as honesty. A single friendly mid-blue accent keeps CTAs warm and human rather than corporate, so the site feels like straightforward help, not a pitch.",
    },
    conversionStrategy: "Straightforward contact-form conversion; no gated content or multi-step funnels.",
    fomoStrategy: "Essentially none — intentionally positioned as the calm, low-pressure option.",
    socialProof: "Short, plain-spoken client quotes focused on reliability rather than transformation.",
    retentionStrategy: "Consistent, dependable service quality is the retention mechanism rather than a program or incentive.",
    brandRecognition: "Minimalist, unbranded tone intentionally fades into the background relative to the other, bolder concepts.",
    competitiveAdvantage: "Captures buyers fatigued by oversold MSP marketing who want a plainly honest alternative.",
  },
  {
    id: "levelup", code: "LVL", name: "Level Up", archetype: "Innocent", theme: "Redline",
    summary: "An experimental concept for the professional recruiting/marketplace side of HDSC, framing career growth as a simple, optimistic, game-like progression rather than a corporate ladder.",
    strategicPurpose: "Serve the professional acquisition funnel (technicians and engineers joining the HDSC marketplace), scoped away from the main customer-facing brand.",
    targetCustomer: "Technicians and engineers seeking flexible, meritocratic work and a visible path to higher-paying opportunities.",
    emotionalPromise: "Optimism — simple, honest belief that good work is visibly rewarded.",
    heroHeadline: "Do Good Work. Watch Your Opportunities Grow.",
    subheadline: "One profile. Real opportunities. A visible path from your first job to your best rate yet.",
    primaryCTA: "Create Your Passport",
    secondaryCTA: "See the Career Ladder",
    urgencyMessage: "Framed positively ('new opportunities post daily — don't miss this week's matches') rather than loss-driven.",
    trustMessage: "Transparent rating and rate history on each professional's own Passport builds trust in the system's fairness.",
    expertiseMessage: "Not about HDSC's expertise, but about surfacing the professional's own growing expertise and track record.",
    differentiation: "The only concept in the portfolio built for suppliers (technicians) rather than buyers (customers).",
    marketplaceExplanation: "Directly explains the two-sided marketplace: opportunities posted by HDSC and clients, bid on by registered professionals.",
    serviceDiscovery: "An opportunity board replaces a service list — professionals browse open bids rather than services.",
    itilIntegration: "Referenced only as a credentialing signal ('ITIL-aligned work experience counts toward your profile').",
    valueCoCreation: "The Professional Passport itself is co-built over time by the professional's own completed work history.",
    customerJourney: "Interest trigger (ad, referral) -> hero/registration -> Passport creation -> opportunity bidding -> work -> ladder advancement.",
    navigation: "Home, Opportunities, Career Ladder, My Passport, Register.",
    homepageSections: "Optimistic hero, 4-step 'how it works' strip, 5-benefit grid, live opportunity preview, register CTA.",
    dashboard: "The Professional Passport itself functions as the dashboard: rating, rate range, matching opportunities, availability.",
    mobileExperience: "Built mobile-first, since most professional users will engage primarily from a phone between jobs.",
    visualDesign: "Redline treatment reused for energy and boldness, but paired with simpler, rounder iconography than the customer-facing Redline concepts to keep an approachable, optimistic feel.",
    colorPalette: {
      label: "Redline — Optimistic Progression",
      background: "#FFFFFF",
      surface: "#F7F7FB",
      primary: "#FF4D5E",
      secondary: "#3DDC97",
      text: "#1F2430",
      mutedText: "#656B7A",
      onPrimary: "#FFFFFF",
      desire: "A light, bright reinterpretation of the Redline family for a career-growth audience: a softened coral-red keeps brand lineage without Command Line's severity, paired with a leveling-up green and achievement gold used sparingly for milestones and badges. Light backgrounds and game-like accent colors create desire through aspiration and visible progress rather than urgency, matching the Innocent archetype's optimistic tone.",
    },
    conversionStrategy: "Passport creation (registration) is the primary conversion, not a sale.",
    fomoStrategy: "Positive FOMO — 'opportunities matching your skills' counters create a sense of momentum rather than scarcity anxiety.",
    socialProof: "Professional success stories showing ladder advancement and rate growth over time.",
    retentionStrategy: "The career ladder itself is the retention mechanic — professionals stay engaged to keep advancing.",
    brandRecognition: "Intentionally lower Brand Fit and Engineering Authority scores reflect that this concept trades some HDSC brand continuity for recruiting-specific appeal — by design, and scoped only to the professional-acquisition side of the business.",
    competitiveAdvantage: "Treats recruiting as a product experience with the same design rigor as the customer-facing marketplace, which most competitors do not do.",
  },
  {
    id: "plainlyput", code: "PLP", name: "Plainly Put", archetype: "Lover", theme: "Figure Isolation",
    summary: "A warm, relationship-first concept emphasizing genuine care and plain-spoken closeness with clients, distinct from Caregiver's protective framing through a more personal, devoted tone.",
    strategicPurpose: "Deepen retention and referral among existing clients by emphasizing the relationship itself as the product.",
    targetCustomer: "Existing clients and warm referrals who value a close, personal vendor relationship over transactional support.",
    emotionalPromise: "Being genuinely known and valued by the people who support your technology.",
    heroHeadline: "We Don't Just Support Your Systems. We Know Them.",
    subheadline: "The same engineers, engagement after engagement — a relationship, not a rotation.",
    primaryCTA: "Meet Your Team",
    secondaryCTA: "Read Client Stories",
    urgencyMessage: "Minimal; this concept is retention- and referral-oriented rather than acquisition-urgent.",
    trustMessage: "Named, consistent engineer assignments and multi-year client relationship tenure are foregrounded as proof.",
    expertiseMessage: "Expertise is demonstrated through depth of familiarity with each specific client's environment over time.",
    differentiation: "The only concept centered on relationship continuity itself as the primary value proposition.",
    marketplaceExplanation: "De-emphasized; this concept presents HDSC as a known, dedicated team rather than a marketplace.",
    serviceDiscovery: "Services are presented through the lens of 'what your dedicated team handles for you' rather than a browsable catalog.",
    itilIntegration: "Service Level Management and Relationship Management practices anchor this concept's ITIL framing.",
    valueCoCreation: "An evolving shared history/timeline of the engagement is presented back to the client as a relationship artifact.",
    customerJourney: "Existing client or warm referral -> relationship-centered landing page -> meet-the-team -> deepen engagement/refer.",
    navigation: "Home, Our Team, Client Stories, Services, Contact.",
    homepageSections: "Warm hero with team imagery, relationship-tenure stats, client story carousel, services-through-relationship framing.",
    dashboard: "A relationship timeline view showing engagement history alongside standard ticket/service data.",
    mobileExperience: "Team photography and story content are prioritized in the mobile layout over dense technical detail.",
    visualDesign: "Figure Isolation treatment shared with On Your Side, but warmer color balance and closer, more personal photography/illustration framing.",
    colorPalette: {
      label: "Figure Isolation — Warm Closeness",
      background: "#FBF5F0",
      surface: "#F3E6DC",
      primary: "#C4685A",
      secondary: "#7B86C7",
      text: "#332420",
      mutedText: "#6B5349",
      onPrimary: "#FFFFFF",
      desire: "Shares On Your Side's Figure Isolation visual family but shifts the balance from cool periwinkle to warm terracotta on a cream ground — the color-temperature equivalent of a closer, more personal relationship. Terracotta and warm cream read as human and devoted rather than corporate, creating desire through intimacy and genuine care for the Lover archetype's relationship-first positioning.",
    },
    conversionStrategy: "Referral generation and renewal are the primary conversions this concept is optimized for.",
    fomoStrategy: "Not applicable by design; this concept intentionally avoids urgency or scarcity framing.",
    socialProof: "Long-tenure client relationship stories, explicitly citing years of partnership.",
    retentionStrategy: "The core purpose of the concept; relationship continuity itself is the retention strategy.",
    brandRecognition: "Shares Figure Isolation's visual language with On Your Side, differentiated by warmer tone and longer-form relationship storytelling.",
    competitiveAdvantage: "Converts satisfied clients into long-term accounts and referral sources more deliberately than any other concept.",
  },
  {
    id: "standard", code: "STD", name: "The Standard", archetype: "Ruler", theme: "Essentialism",
    summary: "HDSC as the disciplined, compliant, standards-driven authority — the concept best suited to underpin the transactional marketplace and account product beneath the marketing site.",
    strategicPurpose: "Provide the structural, trust-maximizing foundation for account creation, contracting, and compliance-sensitive transactions.",
    targetCustomer: "Procurement officers, compliance reviewers, and government/enterprise contracting officials.",
    emotionalPromise: "Certainty — nothing here is improvised; everything is governed.",
    heroHeadline: "Standards You Can Verify. Work You Can Trust.",
    subheadline: "Every engagement is governed by ITIL practice, documented compliance, and a verifiable service standard.",
    primaryCTA: "View Our Compliance Standards",
    secondaryCTA: "Request a Contract Vehicle Overview",
    urgencyMessage: "Minimal; this concept builds trust through thoroughness rather than urgency.",
    trustMessage: "The strongest trust signal in the portfolio: published certifications, UEI/CAGE detail, and a full ITIL practice governance page.",
    expertiseMessage: "Expertise is demonstrated through completeness and precision of documentation, not persuasive copy.",
    differentiation: "The most formal, least emotionally stylized concept in the portfolio — built specifically for compliance-first evaluators.",
    marketplaceExplanation: "Presents the account and contracting structure explicitly: how work is scoped, governed, invoiced, and audited.",
    serviceDiscovery: "A structured, filterable service catalog organized by ITIL practice group and contract vehicle eligibility.",
    itilIntegration: "The deepest ITIL integration of any concept — a dedicated governance section maps every service to its ITIL practice, CompTIA competency, and Six Sigma method.",
    valueCoCreation: "Formal SOWs and service-level agreements are co-developed and version-controlled with the client.",
    customerJourney: "Procurement/compliance research -> standards and governance pages -> capability statement/contract vehicle request -> formal proposal.",
    navigation: "Home, Standards & Governance, Services, Contract Vehicles, Contact.",
    homepageSections: "Formal hero, certifications bar, governance/ITIL mapping summary, service catalog, contract vehicle information.",
    dashboard: "A compliance-oriented account dashboard: active SOWs, audit history, certification status, invoicing.",
    mobileExperience: "Documentation-dense pages are restructured into collapsible accordion sections for mobile legibility.",
    visualDesign: "Essentialism treatment taken to its most formal expression: strict grid layout, minimal color beyond navy/white, data-table-driven presentation.",
    colorPalette: {
      label: "Essentialism — Verified Authority",
      background: "#FFFFFF",
      surface: "#F4F5F7",
      primary: "#0B2447",
      secondary: "#C9A227",
      text: "#0B0B0B",
      mutedText: "#4A4F57",
      onPrimary: "#FFFFFF",
      desire: "The most formal palette in the family: stark white, authoritative deep navy, and a restrained gold used only for certification marks, seals, and verified-standard callouts. Gold is a universal signal of certification and quality in regulatory and compliance contexts, so its scarcity here (never used decoratively) creates desire through perceived rigor — exactly what the Ruler archetype needs to anchor the transactional marketplace and account product beneath it.",
    },
    conversionStrategy: "Capability statement and contract-vehicle-overview requests are the primary conversions, matching procurement workflows.",
    fomoStrategy: "None by design; compliance buyers respond to thoroughness, not urgency.",
    socialProof: "Certifications, audit results, and named contract vehicle participation substitute for conventional testimonials.",
    retentionStrategy: "Contract renewal cycles and standing compliance documentation keep HDSC embedded in procurement systems.",
    brandRecognition: "The least visually distinctive concept by design — recognition here comes from consistency and documentation quality, not visual flourish.",
    competitiveAdvantage: "Directly answers the compliance and governance scrutiny that other concepts in the portfolio do not attempt to satisfy.",
  },
  {
    id: "enterprisegrid", code: "ENT", name: "The Enterprise Grid", archetype: "Ruler", theme: "Corporate Grid (new — matches live site)",
    summary: "A concept built to match the visual language of HDSC's current live website: a dark navy navigation bar over clean white content, a card-grid of strategic business units, and an authoritative, compliance-forward enterprise tone.",
    strategicPurpose: "Preserve continuity with the company's existing live site and current market-facing identity while bringing it into the same structured concept framework as the other 12 concepts, so it can be fairly compared and, if desired, refined rather than replaced.",
    targetCustomer: "Enterprise and government buyers evaluating HDSC across a broad portfolio of business units — IT/MSP, cybersecurity, cloud, systems and software engineering, data and analytics, ML/AI security, and aerospace and defense.",
    emotionalPromise: "Confidence in scale — the sense that HDSC is a full-portfolio engineering firm, not a single-service vendor.",
    heroHeadline: "Elite Security & IT Solutions.",
    subheadline: "Comprehensive physical and cybersecurity infrastructure management across eleven strategic business units.",
    primaryCTA: "Request a Quote",
    secondaryCTA: "View Strategic Business Units",
    urgencyMessage: "Minimal in the current live site; this concept keeps that tone but adds a light response-time or availability cue to the hero if the company wants to increase conversion pressure later.",
    trustMessage: "Certification and compliance badges, displayed prominently, are the current site's central trust mechanism and are preserved here.",
    expertiseMessage: "Breadth of the eleven business units (IT Services/MSP, Cybersecurity, Cloud & Infrastructure, Systems Engineering, Software Engineering, Data & Analytics, ML/AI Security, Aerospace & Defense, and others) communicates expertise through scope.",
    differentiation: "The only concept in the portfolio directly continuous with HDSC's existing public-facing brand, making it the lowest-risk, lowest-disruption option if the company wants to evolve rather than replace its current site.",
    marketplaceExplanation: "Presented as a portfolio of strategic business units a buyer can engage individually or together, rather than a single undifferentiated service list.",
    serviceDiscovery: "A card-based grid of strategic business units (matching the current live site's structure) lets a visitor self-select into the relevant practice area.",
    itilIntegration: "Not currently present on the live site; this concept recommends layering in ITIL practice labeling within each business-unit card as a direct enhancement, without changing the overall visual structure.",
    valueCoCreation: "Not currently present on the live site; recommended as a future enhancement (a client-specific service summary) consistent with the enterprise tone.",
    customerJourney: "Search or referral -> hero -> strategic business unit grid -> compliance/certification review -> contact/quote form.",
    navigation: "Home, Strategic Business Units, Compliance & Standards, Contact — matching the current site's structure.",
    homepageSections: "Hero banner, strategic business unit card grid (11 areas), compliance/certification badge section, contact/inquiry forms, footer with location and contact detail.",
    dashboard: "Not present on the current live site; could be added as a future account layer without disrupting the existing public-facing structure.",
    mobileExperience: "Card grid collapses to a single column; navy nav bar remains fixed at the top for orientation, consistent with the current site's behavior.",
    visualDesign: "Corporate Grid treatment: dark navy top navigation over white content areas, card-based layout for service/business-unit sections, abstract technology and security imagery, high-contrast professional B2B aesthetic.",
    colorPalette: {
      label: "Corporate Grid — Enterprise Confidence",
      background: "#FFFFFF",
      surface: "#F5F7FA",
      primary: "#0A1F44",
      secondary: "#1E6FD9",
      tertiary: "#00B8A9",
      text: "#16213E",
      mutedText: "#55617A",
      onPrimary: "#FFFFFF",
      desire: "Matches the live Wix site's established visual language — a dark navy top navigation bar over clean white content, with corporate blue for primary actions and a security-forward teal for highlighted capability cards. This is the most conventional, large-enterprise-procurement-friendly palette in the set: a deliberately safe, high-contrast professional B2B aesthetic that creates desire through category-norm credibility rather than brand distinctiveness.",
    },
    conversionStrategy: "Multiple quote-request CTAs distributed across the business-unit grid, matching the current site's pattern of per-section inquiry prompts.",
    fomoStrategy: "Not currently used on the live site; largely absent from this concept by design, consistent with its formal, enterprise register.",
    socialProof: "Currently limited to certification/compliance badges rather than client testimonials; a recommended enhancement is adding named case studies without changing the visual system.",
    retentionStrategy: "Not addressed on the current live site; recommended as a future addition (a client portal or account area) layered onto the existing structure.",
    brandRecognition: "Directly recognizable as HDSC's current public identity; the benchmark concept against which all 12 new concepts should be judged for brand continuity versus evolution.",
    competitiveAdvantage: "Demonstrates the eleven-business-unit breadth immediately and familiarly, with zero transition risk since it reflects what buyers can already find when they search for HDSC today.",
  },
];

const MATRIX_CATEGORIES = [
  "Brand Fit",
  "Customer Clarity",
  "B2B Appeal",
  "Marketplace Clarity",
  "ITIL Integration",
  "Engineering Authority",
  "Conversion Potential",
  "FOMO / Urgency",
  "Trust",
  "Differentiation",
  "Brand Recognition",
  "Mobile Adaptability",
  "Accessibility",
  "Scalability",
  "Long-Term Brand Value",
];

// Each array aligns 1:1 with MATRIX_CATEGORIES, scored 1 (low) - 10 (high).
const SCORES = {
  signal:         [9, 9, 8, 8, 6, 8, 9, 9, 8, 8, 9, 8, 8, 9, 9],
  blueprint:      [9, 7, 9, 8, 10, 10, 7, 5, 9, 8, 7, 6, 7, 8, 9],
  onyourside:     [8, 9, 6, 6, 4, 5, 7, 4, 8, 7, 7, 8, 8, 6, 7],
  commandline:    [8, 7, 8, 7, 6, 8, 8, 8, 7, 8, 8, 7, 6, 8, 8],
  thefix:         [6, 8, 7, 5, 4, 6, 8, 8, 6, 9, 7, 7, 6, 6, 5],
  frontier:       [8, 8, 8, 6, 6, 7, 7, 5, 7, 7, 7, 7, 7, 9, 8],
  nopatience:     [4, 7, 5, 3, 2, 3, 7, 7, 5, 9, 6, 9, 5, 4, 4],
  builtby:        [8, 7, 8, 5, 7, 9, 6, 3, 8, 7, 7, 6, 6, 7, 8],
  anyonesengineer:[6, 8, 5, 4, 5, 5, 6, 2, 7, 4, 5, 8, 9, 7, 6],
  levelup:        [4, 8, 4, 7, 3, 3, 8, 7, 6, 8, 6, 9, 7, 8, 5],
  plainlyput:     [7, 8, 6, 4, 5, 5, 6, 2, 8, 6, 6, 7, 7, 6, 7],
  standard:       [9, 8, 9, 8, 9, 9, 7, 5, 10, 7, 7, 8, 8, 9, 9],
  enterprisegrid: [10, 6, 8, 5, 3, 7, 6, 3, 7, 4, 10, 6, 6, 7, 6],
};

module.exports = { FIELD_ORDER, CONCEPTS, MATRIX_CATEGORIES, SCORES };
